services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - PYTHONPATH=/app
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    ports:
      - "8080:8080"

  # Optional: Playwright in Docker (if you want to run it containerized)
  # playwright:
  #   image: mcr.microsoft.com/playwright:v1.44.1-focal
  #   depends_on:
  #     - backend
  #   entrypoint: ["npx", "playwright", "test"]
