name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t file-resizer-app -f backend/Dockerfile .
      
    - name: Run Tests Inside Container
      run: docker run --rm -e PYTHONPATH=/app file-resizer-app pytest tests